"""admin

Revision ID: 165a2476691c
Revises: 8dcc4fd25324
Create Date: 2021-10-19 14:56:20.783100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165a2476691c'
down_revision = '8dcc4fd25324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(length=200), nullable=True))
    op.add_column('admin', sa.Column('password', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
