"""'Initial'

Revision ID: 68f67ec32e7c
Revises: 
Create Date: 2021-10-12 02:49:23.476117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f67ec32e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('template_email', sa.Integer(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id_customer'], ),
    sa.ForeignKeyConstraint(['template_email'], ['template.id_template'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_foreign_key(None, 'template', 'status', ['status'], ['id_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.drop_table('log')
    # ### end Alembic commands ###
