"""RELATIONSHIP CASCADE

Revision ID: 79dd4491d2b8
Revises: 960c48b0ca08
Create Date: 2021-10-22 08:29:18.503005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dd4491d2b8'
down_revision = '960c48b0ca08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_ibfk_2', 'customer', type_='foreignkey')
    op.drop_constraint('customer_ibfk_1', 'customer', type_='foreignkey')
    op.drop_constraint('customer_ibfk_3', 'customer', type_='foreignkey')
    op.drop_constraint('customer_ibfk_4', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'pekerjaan', ['jenis_pekerjaan'], ['id_pekerjaan'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'customer', 'prov', ['prov_domisili'], ['kode_prov'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'customer', 'pendidikan', ['pendidikan'], ['id_pendidikan'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'customer', 'kabkot', ['kab_domisili'], ['id_kabkot'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('kabkot_ibfk_1', 'kabkot', type_='foreignkey')
    op.create_foreign_key(None, 'kabkot', 'prov', ['kode_prov'], ['kode_prov'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('log_ibfk_1', 'log', type_='foreignkey')
    op.drop_constraint('log_ibfk_3', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'customer', ['customer'], ['id_customer'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'log', 'status', ['status'], ['id_status'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('template_ibfk_1', 'template', type_='foreignkey')
    op.create_foreign_key(None, 'template', 'status', ['status'], ['id_status'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.create_foreign_key('template_ibfk_1', 'template', 'status', ['status'], ['id_status'])
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_ibfk_3', 'log', 'status', ['status'], ['id_status'])
    op.create_foreign_key('log_ibfk_1', 'log', 'customer', ['customer'], ['id_customer'])
    op.drop_constraint(None, 'kabkot', type_='foreignkey')
    op.create_foreign_key('kabkot_ibfk_1', 'kabkot', 'prov', ['kode_prov'], ['kode_prov'])
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_ibfk_4', 'customer', 'kabkot', ['kab_domisili'], ['id_kabkot'])
    op.create_foreign_key('customer_ibfk_3', 'customer', 'prov', ['prov_domisili'], ['kode_prov'])
    op.create_foreign_key('customer_ibfk_1', 'customer', 'pendidikan', ['pendidikan'], ['id_pendidikan'])
    op.create_foreign_key('customer_ibfk_2', 'customer', 'pekerjaan', ['jenis_pekerjaan'], ['id_pekerjaan'])
    # ### end Alembic commands ###
