"""admin

Revision ID: 8dcc4fd25324
Revises: 6784ee3e4574
Create Date: 2021-10-19 14:54:47.667138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dcc4fd25324'
down_revision = '6784ee3e4574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'username')
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('admin', sa.Column('username', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
