"""admin db

Revision ID: 960c48b0ca08
Revises: a13b9cee13f7
Create Date: 2021-10-19 14:58:09.093816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960c48b0ca08'
down_revision = 'a13b9cee13f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_admin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
